name: NPM Publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    if: ${{ contains(github.event.head_commit.message, 'Update version') }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - run: yarn
      - run: yarn upgrade @steroidsjs/core
      - run: yarn tsc
      - run: yarn docs
      - run: cp ./{package.json,LICENSE,README.md} dist/
      - run: cp src/index.d.ts dist/
      - run: cp docs/docs-autogen-result.json dist/
      - run: cp docs/locales/en.json dist/
      - uses: JS-DevTools/npm-publish@v4
        with:
          package: ./dist/package.json
