name: NPM Publish
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: yarn
      - run: yarn build
      - run: npm test
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: ./dist/package.json
          token: ${{ secrets.NPM_TOKEN }}