name: NPM Publish
on:
  push:
    branches:
      - 'master'
      - 'v2'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ^14.15.0 || ^16.10.0 || >=18.0.0
      - run: yarn
      - run: yarn upgrade @steroidsjs/core
      - run: yarn tsc
      - run: cp ./{package.json,LICENSE,README.md} dist/
      - run: cp src/index.d.ts dist/
      - run: cp docs/docs-autogen-result.json dist/
      - run: cp docs/locales/en.json dist/
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: ./dist/package.json
          token: ${{ secrets.NPM_TOKEN }}
