name: Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: steroids/react-bootstrap
          ref: hooks
          path: react-bootstrap
      - run: yarn
      - run: pwd
      - run: yarn test