name: Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max-old-space-size=4096"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: steroids/react-bootstrap
          ref: master
          path: react-bootstrap
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn
      - run: cd react-bootstrap && yarn test
