name: Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: steroids/react-bootstrap
          ref: master
          path: react-bootstrap
      - run: |
          echo "::set-env name=NODE_OPTIONS::--max-old-space-size=4096"
          yarn
          cd react-bootstrap && yarn test
        env:
          NODE_OPTIONS: --max-old-space-size=4096
